"""
Populates the master .pptx template with proposal content generated by Claude.

PLACEHOLDER CONVENTION:
All dynamic text in master.pptx uses {{PLACEHOLDER_NAME}} syntax.
build_context() maps every placeholder to a value from the Claude output + brief.

SLIDE MAP:
  Slide 1  — Cover:            PROSPECT_NAME, ACCOUNT_MANAGER
  Slide 2  — Engagement:       PROSPECT_NAME, CONTACT_NAME, START_DATE,
                                ACCOUNT_MANAGER, ACCOUNT_MANAGER_EMAIL
  Slide 3  — Where You Are Now (intro): BRAND_SUMMARY
  Slide 4  — Three Realities:  REALITY_1_TITLE/TEXT, REALITY_2_TITLE/TEXT, REALITY_3_TITLE/TEXT
  Slide 5  — The Plan:         PLAN_1-5_TITLE, PLAN_1-5_ITEMS
  Slide 8  — Investment:       COST_LINE_1_NAME/DESC/PRICE, TOTAL_INVESTMENT
  Slide 10 — Deliverables:     DELIVERABLES_1-4_TITLE, DELIVERABLES_1-4_ITEMS
  Slide 11 — How We Work:      TIMELINE, OUT_OF_SCOPE
  Slide 12 — To Get Started:   START_ITEM_1-6_TITLE, START_ITEM_1-6_TEXT (if dynamic)
"""

from pathlib import Path
from pptx import Presentation
from pptx.util import Pt
from pptx.enum.text import PP_ALIGN
from pptx.oxml.ns import qn
from lxml import etree

TEMPLATE_PATH = Path(__file__).parent.parent / "pptx_template" / "master.pptx"


def _enable_autofit(text_frame):
    """
    Set the text frame to shrink text to fit the shape bounds.
    This prevents overflow when generated content is longer than the placeholder.
    """
    tf = text_frame._txBody
    bodyPr = tf.find(qn("a:bodyPr"))
    if bodyPr is not None:
        # Remove any existing sizing attributes
        for attr in ("spAutoFit", "normAutofit", "noAutofit"):
            existing = bodyPr.find(qn(f"a:{attr}"))
            if existing is not None:
                bodyPr.remove(existing)
        # Add normAutofit — shrinks text to fit without changing box size
        etree.SubElement(bodyPr, qn("a:normAutofit"))


def _replace_text_in_shape(shape, replacements: dict):
    """
    Replace {{TOKEN}} in a shape's text frame, preserving run-level formatting.
    Enables auto-fit on any frame where a replacement was made.
    """
    if not shape.has_text_frame:
        return
    replaced = False
    for para in shape.text_frame.paragraphs:
        for run in para.runs:
            for key, value in replacements.items():
                token = f"{{{{{key}}}}}"
                if token in run.text:
                    run.text = run.text.replace(token, str(value))
                    replaced = True
    if replaced:
        _enable_autofit(shape.text_frame)


def _replace_in_slide(slide, replacements: dict):
    for shape in slide.shapes:
        _replace_text_in_shape(shape, replacements)
        if shape.shape_type == 6:  # GROUP
            for s in shape.shapes:
                _replace_text_in_shape(s, replacements)


def _bullet_list(items: list) -> str:
    """Formats a list of strings as newline-separated bullet lines."""
    return "\n".join(f"- {item}" for item in items if item)


def build_context(proposal: dict, brief: dict) -> dict:
    """
    Flattens the Claude proposal JSON + brief into a flat dict of
    PLACEHOLDER_NAME -> replacement string, covering every slide.
    """
    from datetime import datetime

    # --- Cover / Engagement ---
    context = {
        "PROSPECT_NAME":       proposal.get("prospect_name", brief.get("prospect_name", "")),
        "ACCOUNT_MANAGER":     brief.get("account_manager", ""),
        "ACCOUNT_MANAGER_EMAIL": brief.get("account_manager_email", ""),
        "CONTACT_NAME":        brief.get("contact_name", ""),
        "START_DATE":          proposal.get("start_date", "TBC"),
        "PREPARED_DATE":       datetime.now().strftime("%B %Y").upper(),
    }

    # --- Where You Are Now (intro) ---
    context["BRAND_SUMMARY"] = proposal.get("brand_summary", "")

    # --- Three Realities (slide 4) ---
    realities = proposal.get("realities", [{}, {}, {}])
    for i, reality in enumerate(realities[:3], start=1):
        context[f"REALITY_{i}_TITLE"] = reality.get("title", "")
        context[f"REALITY_{i}_TEXT"]  = reality.get("text", "")

    # --- The Plan (slide 5) — always 5 phases ---
    plan = proposal.get("plan", [{}, {}, {}, {}, {}])
    for i, phase in enumerate(plan[:5], start=1):
        context[f"PLAN_{i}_TITLE"] = phase.get("title", "")
        context[f"PLAN_{i}_ITEMS"] = _bullet_list(phase.get("items", []))

    # --- Investment (slide 8) ---
    cost = proposal.get("cost", {})
    context["COST_LINE_1_NAME"]  = cost.get("line_1_name", "")
    context["COST_LINE_1_DESC"]  = cost.get("line_1_desc", "")
    context["COST_LINE_1_PRICE"] = cost.get("line_1_price", "")
    context["TOTAL_INVESTMENT"]  = cost.get("total", "")

    # --- Deliverables (slide 10) — always 4 columns ---
    deliverables = proposal.get("deliverables", [{}, {}, {}, {}])
    for i, col in enumerate(deliverables[:4], start=1):
        context[f"DELIVERABLES_{i}_TITLE"] = col.get("title", "")
        context[f"DELIVERABLES_{i}_ITEMS"] = _bullet_list(col.get("items", []))

    # --- How We Work (slide 11) ---
    context["TIMELINE"]     = proposal.get("timeline", "")
    context["OUT_OF_SCOPE"] = proposal.get("out_of_scope", "")

    # --- To Get Started (slide 12) — 6 items, dynamic if provided ---
    to_get_started = proposal.get("to_get_started", [])
    for i, item in enumerate(to_get_started[:6], start=1):
        context[f"START_ITEM_{i}_TITLE"] = item.get("title", "")
        context[f"START_ITEM_{i}_TEXT"]  = item.get("text", "")

    return context


def generate_pptx(proposal: dict, brief: dict, output_path: Path) -> Path:
    """
    Loads master.pptx, replaces all placeholders, saves to output_path.
    Returns the output path.
    """
    if not TEMPLATE_PATH.exists():
        raise FileNotFoundError(
            f"Master template not found at {TEMPLATE_PATH}. "
            "Add master.pptx to the pptx_template/ folder."
        )

    prs = Presentation(str(TEMPLATE_PATH))
    replacements = build_context(proposal, brief)

    for slide in prs.slides:
        _replace_in_slide(slide, replacements)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(output_path))
    return output_path
